# .streamlit/secrets.toml

EMAIL_ADDRESS = "aliashari0304@gmail.com"
EMAIL_PASSWORD = "mqub vnru brju gtxr " # Untuk Gmail, ini adalah App Password
SMTP_SERVER = "smtp.gmail.com" # Ganti jika bukan Gmail
SMTP_PORT = 465 # Atau 587 untuk TLS, tergantung server
